logging:
  outputLevel: "debug"

# Chain network configuration
chain:
  name: "endurance-devnet"
  configPath: "/el-cl-genesis-data/metadata/config.yaml"
  displayName: "Endurance Devnet"

# HTTP Server configuration
server:
  host: "0.0.0.0" # Address to listen on
  port: "8080" # Port to listen on

frontend:
  enabled: true # Enable or disable to web frontend
  debug: false
  minimize: false # minimize html templates

  # Name of the site, displayed in the title tag
  siteName: "Endurance Devnet"
  siteSubtitle: "Dora the Explorer"

  # link to EL Explorer
  ethExplorerLink: ""
  rainbowkitProjectId: "7ef7824583418b0e3914c981bd833ace"

  # file or inventory url to load validator names from
  # validatorNamesYaml: "/validator-ranges/validator_names.yaml"

  # Electra related
  showSubmitDeposit: true
  showSubmitElRequests: true

beaconapi:
  # CL Client RPC
  endpoints:
    # 容器内访问host服务
    - url: "http://host.docker.internal:4000"
      name: "geth-lighthouse"
      archive: true

  # local cache for page models
  localCacheSize: 10 # 10MB

  # remote cache for page models
  redisCacheAddr: ""
  redisCachePrefix: ""

executionapi:
  # execution node rpc endpoints
  endpoints:
    - name: "local"
      url: "http://host.docker.internal:8545"

  # batch size for log event calls
  depositLogBatchSize: 1000
  depositDeployBlock: 0 # el block number from where to crawl the deposit contract (should be <=, but close to the deposit contract deployment block)
  electraDeployBlock: 0 # el block number from where to crawl the electra system contracts (should be <=, but close to electra fork activation block)

# indexer keeps track of the latest epochs in memory.
indexer:
  # max number of epochs to keep in memory
  inMemoryEpochs: 8

  # number of epochs to wait before storing unfinalized blocks to db
  cachePersistenceDelay: 8

  # disable synchronizing and everything that writes to the db (indexer just maintains local cache)
  disableIndexWriter: false

  # number of seconds to wait between each epoch (don't overload CL client)
  syncEpochCooldown: 1

database:
  engine: "sqlite"
  sqlite:
    file: "/dora-database.sqlite"
