version: "3.8"

services:
  execution:
    image: nethermindeth/nethermind:release-1.31.9
    command:
      - --log=INFO
      - --datadir=/execution-data
      - --Init.ChainSpecPath=/el-cl-genesis-data/custom_config_data/chainspec.json
      - --Init.WebSocketsEnabled=true
      - --config=none.cfg
      - --JsonRpc.Enabled=true
      - --JsonRpc.EnabledModules=net,eth,consensus,subscribe,web3,admin,debug
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.WebSocketsPort=8546
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
      - --JsonRpc.JwtSecretFile=/el-cl-genesis-data/jwt/jwtsecret
      - --Network.ExternalIp=${IP_ADDRESS}
      - --Network.DiscoveryPort=30303
      - --Network.P2PPort=30303
      - --Metrics.Enabled=true
      - --Metrics.ExposePort=9001
      - --Network.StaticPeers=${EL_BOOTNODES}
      - --Sync.SnapSync=false
    volumes:
      - ./execution-data:/execution-data
      - ../el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "8545:8545" 
      - "8546:8546" 
      - "8551:8551" 
      - "9001:9001" 
      - "30303:30303"
    restart: unless-stopped

  beacon:
    image: sigp/lighthouse:v7.0.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=10000
      - --enr-tcp-port=10000
      - --enr-quic-port=10001
      - --listen-address=0.0.0.0
      - --port=10000
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --http-allow-sync-stalled
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x55A4255DcD8e41B588Fb54E11Afc8A34D791ab1d
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=${CL_TRUSTPEERS}
      - --boot-nodes=${CL_BOOTNODES}
      - --subscribe-all-subnets
      - --import-all-attestations
    volumes:
      - ./consensus-data:/consensus-data 
      - ../el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10001:10001/udp"
      - "5052:5052"
      - "5054:5054"
    depends_on:
      - execution
    restart: unless-stopped

  validator:
    image: sigp/lighthouse:v7.0.0
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator_keys
      - --secrets-dir=/secrets
      - --http
      - --http-address=0.0.0.0
      - --http-port=5062
      - --unencrypted-http-transport
      - --init-slashing-protection
      - --beacon-nodes=http://beacon:5052
      - --suggested-fee-recipient=0x55A4255DcD8e41B588Fb54E11Afc8A34D791ab1d
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5064
      - --graffiti=Nethermind-Lighthouse
    volumes:
      - ../el-cl-genesis-data:/el-cl-genesis-data
      - ./validator_keys:/validator_keys
      - ./secrets:/secrets
    ports:
      - "5062:5062"
      - "5064:5064"
    depends_on:
      - beacon
    restart: unless-stopped