# ref: https://github.com/flashbots/rbuilder/blob/develop/docs/CONFIG.md
# use: ./rbuilder run config.toml

log_level = "info,rbuilder=debug"
log_color = true
redacted_telemetry_server_port = 6061
redacted_telemetry_server_ip = "0.0.0.0"
full_telemetry_server_port = 6060
full_telemetry_server_ip = "0.0.0.0"

# for custom chain, use genesis file path
chain = "../el-cl-genesis-data/custom_config_data/genesis.json"
reth_datadir = "./execution-data"

relay_secret_key = "0x51da11b45a7219cc61a3d9c5fd08c7eebd602a6a19a977f8d3771d5711a55123"


# cl_node_url can be a single value, array of values, or passed by an environment variables with values separated with a comma
cl_node_url = "http://localhost:5052"
# cl_node_url = ["env:CL_NODE_URL"]
jsonrpc_server_port = 8645
jsonrpc_server_ip = "0.0.0.0"
el_node_ipc_path = "./execution-data/reth.ipc"
extra_data = "pectra-devnet-1-builder"

ignore_cancellable_orders = true

# ref:https://collective.flashbots.net/t/announcing-multi-client-support-for-rbuilder/4895
watchdog_timeout_sec = 600
simulation_threads = 4

sbundle_mergeable_signers = []
live_builders = ["mp-ordering", "mgp-ordering"]

enabled_relays = ["local-relay"]

# fix: Error: root_hash_use_sparse_trie=true and root_hash_compare_sparse_trie=false must be set, otherwise node will produce incorrect blocks or confusing error messages. These settings are enforced temporarily because upstream parallel root hash implementation is not correct.
root_hash_use_sparse_trie = true
root_hash_compare_sparse_trie = false

# ref: https://github.com/flashbots/rbuilder/blob/develop/config-optimism-local.toml
[[relays]]
name = "local-relay"
url = " http://0x8aaa802de39ce9ab3f0fe937681bff1ec325894a5471ead6dd91c2e7465cf26a3a9cd24478837fe24fac957e014aa3bb@20.195.2.236:9062"
# priority = 0 2025-04-25T12:25:29.155778Z  WARN rbuilder::live_builder::config: Deprecated: relay priority set, ignoring relay="local-relay"

[[builders]]
name = "mgp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "mev-gas-price"
failed_order_retries = 1
drop_failed_orders = true

[[builders]]
name = "mp-ordering"
algo = "ordering-builder"
discard_txs = true
sorting = "max-profit"
failed_order_retries = 1
drop_failed_orders = true
