services:
  execution:
    image: ethpandaops/reth-rbuilder:develop
    command:
      - node
      - -vvv
      - --datadir=/execution-data
      - --chain=/el-cl-genesis-data/custom_config_data/genesis.json
      - --addr=0.0.0.0
      - --port=30303
      - --discovery.port=30303
      - --discovery.addr=0.0.0.0
      - --http
      - --http.port=8545
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --http.api=net,eth,web3,debug,trace,flashbots
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=net,eth,flashbots
      - --ws.origins=*
      - --nat=extip:${IP_ADDRESS}
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --authrpc.addr=0.0.0.0
      - --metrics=0.0.0.0:9001
      - --bootnodes=${EL_BOOTNODES}
      - --trusted-peers=${EL_BOOTNODES}
      - --ipcpath=/execution-data/reth.ipc
      - --rbuilder.config=/rbuilder.toml
      - --engine.persistence-threshold=0
      - --engine.memory-block-buffer-target=0
      - --txpool.no-local-transactions-propagation
    volumes:
      - ./execution-data:/execution-data
      - ../el-cl-genesis-data:/el-cl-genesis-data
      - ./rbuilder.toml:/rbuilder.toml
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "9001:9001"
      - "30303:30303"
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 1m

  beacon:
    image: sigp/lighthouse:v7.0.0
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=10000
      - --enr-tcp-port=10000
      - --enr-quic-port=10001
      - --listen-address=0.0.0.0
      - --port=10000
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --http-allow-origin=*
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x55A4255DcD8e41B588Fb54E11Afc8A34D791ab1d
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=${CL_TRUSTPEERS}
      - --boot-nodes=${CL_BOOTNODES}
      - --subscribe-all-subnets
      - --import-all-attestations
      - --checkpoint-sync-url=${CL_CHECKPOINTZ_URL}
      # ref: https://github.com/flashbots/rbuilder
      - --always-prepare-payload
      # ref: https://github.com/flashbots/mev-boost-relay
      - --prepare-payload-lookahead=12000
    volumes:
      - ./consensus-data:/consensus-data
      - ../el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10000:10000/tcp"
      - "10000:10000/udp"
      - "10001:10001/udp"
      - "5052:5052"
      - "5054:5054"
    depends_on:
      - execution
    restart: unless-stopped
