global:
  listenAddr: ":5555"
  logging: "info" # panic,fatal,warm,info,debug,trace
  metricsAddr: ":9090"

checkpointz:
  mode: full
  caches:
    blocks:
      max_items: 200
    states:
      max_items: 5
  historical_epoch_count: 20
  frontend:
    # if the frontend should served
    enabled: true
    # brand logo to display on the frontend (optional)
    brand_image_url:
    # brand to display on the frontend (optional)
    brand_name: Brandname
    # public url where frontend will be served from (optional)
    public_url: http://135.181.2.253:9781

beacon:
  upstreams:
    - name: geth-prysm
      address: http://135.181.2.253:4000
      timeoutSeconds: 30
      dataProvider: true
    - name: nethermind-lighthouse
      address: http://65.108.127.114:5052
      timeoutSeconds: 30
      dataProvider: true
    - name: besu-lodestar
      address: http://57.155.181.23:4000
      timeoutSeconds: 30
      dataProvider: true

      # headers:
      #  header_name: header_value
